//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Person_ID { get; set; }
        public string Name { get; set; }
        public int NationalId { get; set; }
        public int Age { get; set; }
        public int PersonalCode { get; set; }
        public int PhoneNumber { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string LastName { get; set; }
        public bool Active { get; set; }
        public int OldNI { get; set; }
    }
}
