//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServerComponent
    {
        public long ServerComponent_ID { get; set; }
        public int Server_ID { get; set; }
        public string ComponentName { get; set; }
        public int Component_ID { get; set; }
        public bool Active { get; set; }
    
        public virtual Servers Servers { get; set; }
    }
}
