//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Server
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Server()
        {
            this.ServerComponents = new HashSet<ServerComponent>();
        }
    
        public int Server_ID { get; set; }
        public string Name { get; set; }
        public string SerialNumber { get; set; }
        public string DatePurchased { get; set; }
        public string TechSupportNo { get; set; }
        public string MakeModel { get; set; }
        public string AssetTagNumber { get; set; }
        public string WarrantyExpirationDate { get; set; }
        public bool Active { get; set; }
        public string RegisterDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServerComponent> ServerComponents { get; set; }
    }
}
