//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace API
{
    using System;
    using System.Collections.Generic;
    
    public partial class Users
    {
        public long User_ID { get; set; }
        public string Name { get; set; }
        public string Pass { get; set; }
        public short Role2 { get; set; }
        public short Role1 { get; set; }
        public bool Active { get; set; }
        public long Person_ID { get; set; }
    }
}
